name: 6000.0.37f1-Player

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './Unity-Theme'
      unityVersion: '6000.0.37f1'
      testMode: 'playmode'
    secrets: inherit