name: test-pull-request

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  # --- EDIT MODE ---

  test-unity-2022-3-61f1-editmode:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '2022.3.61f1'
      testMode: 'editmode'
    secrets: inherit

  test-unity-2023-2-20f1-editmode:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '2023.2.20f1'
      testMode: 'editmode'
    secrets: inherit

  test-unity-6000-2-3f1-editmode:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '6000.2.3f1'
      testMode: 'editmode'
    secrets: inherit

  # --- PLAY MODE ---

  test-unity-2022-3-61f1-playmode:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '2022.3.61f1'
      testMode: 'playmode'
    secrets: inherit

  test-unity-2023-2-20f1-playmode:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '2023.2.20f1'
      testMode: 'playmode'
    secrets: inherit

  test-unity-6000-2-3f1-playmode:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '6000.2.3f1'
      testMode: 'playmode'
    secrets: inherit

  # --- STANDALONE ---

  test-unity-2022-3-61f1-standalone:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '2022.3.61f1'
      testMode: 'standalone'
    secrets: inherit

  test-unity-2023-2-20f1-standalone:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '2023.2.20f1'
      testMode: 'standalone'
    secrets: inherit

  test-unity-6000-2-3f1-standalone:
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: './Unity-Theme-Plugin'
      unityVersion: '6000.2.3f1'
      testMode: 'standalone'
    secrets: inherit

  # -------------------